### ISSUE TITLE
Licence File

### ISSUE THREAD

**Issue by dwhiting10** [chrisbottin/xml-formatter#10]
I see that in your README.md that xml-formatter is licensed under the MIT license, but there isn't a license file in the repo (that I could find).  Would it be possible to add one?  The project I am working requires us to be able to point to a license file for any 3rd party code we include in our work.

Thanks!

**Comment by chrisbottin** [comment]
Added in version https://github.com/chrisbottin/xml-formatter/releases/tag/1.2.0

**Comment by dwhiting10** [comment]
Thanks!
