### ISSUE TITLE
CDATA not being handled correctly

### ISSUE THREAD

**Issue by maxkreja** [chrisbottin/xml-formatter#11]
If the XML contains a CDATA tag the formatter won't output the tag and any other XML tags after the CDATA tag.

Example Input:

```xml
<root><![CDATA[some text]]><child><subchild/></child></root>
```

Example Output:

```xml
<root>
</root>
```

Expected Output:

```xml
<root>
  <![CDATA[some text]]>
  <child>
    <subchild/>
  </child>
</root>
```

Info:
- Node.js: 12.13.0
- xml-formatter: 1.1.0

**Comment by maxkreja** [comment]
Issue seems related to segmentio/xml-parser#25

**Comment by chrisbottin** [comment]
Thanks for the information. I will provide a fix shortly but can't give you any timescale.

**Comment by chrisbottin** [comment]
This should be fixed by #15

**Comment by sp53519** [comment]
Checked in version 2.1.0. The problem is relevant.

**Comment by CatalinMustata** [comment]
Works in 2.4.0
