### ISSUE TITLE
Idempotence

### ISSUE THREAD

**Issue by hediet** [chrisbottin/xml-formatter#17]
It would be cool if `formatter(formatter(source)) = formatter(source)`.
I'm looking for a way to test whether two xml documents are the same except their formatting.
Sadly, your library is not idempotent:

![image](https://user-images.githubusercontent.com/2931520/81555535-0b715200-9389-11ea-84ef-a3741b09b798.png)

So I cannot use format function to canonicalize xml documents.

**Comment by chrisbottin** [comment]
Hi,

Have you tried the latest version v2.0.1 as a fix was added for something similar.

https://github.com/chrisbottin/xml-formatter/pull/16/files#diff-910eb6f57886ca16c136101fb1699231R48

**Comment by hediet** [comment]
I'm using v2.0.1 in the screenshot.

**Comment by chrisbottin** [comment]
OK, I will take a look. it might be a simple fix.

**Comment by chrisbottin** [comment]
This issue is fixed in version [2.1.1](https://github.com/chrisbottin/xml-formatter/tree/2.1.1) (commit 8d644d8)
