### ISSUE TITLE
Would be awesome if you updated the .d.ts file when you make improvements, too!

### ISSUE THREAD

**Issue by Benjin** [chrisbottin/xml-formatter#19]
Makes the lives of us typescript devs even better :)

**Comment by Benjin** [comment]
https://github.com/Benjin/DefinitelyTyped/tree/master/types/xml-formatter

Looks like it's drifted a bit

**Comment by chrisbottin** [comment]
Sure... actually I might convert this code to TypeScript.

**Comment by chrisbottin** [comment]
A TypeScript declaration file has been added in version 2.1.1 until the code is converted to TypeScript.
