### ISSUE TITLE
Integrate node-expat

### ISSUE THREAD

**Issue by xamgore** [chrisbottin/xml-formatter#25]
[`node-expat`](https://github.com/astro/node-expat) will speed up the formatter. Usage examples may be found in the [`xml2json`](https://github.com/buglabs/node-xml2json) package.

**Comment by chrisbottin** [comment]
Thanks for the suggestion. I had a look at the package and the file size seems too heavy to use as a dependency inside xml-parser-xo or even replace it.

**Comment by xamgore** [comment]
It could be imported as an optional dependency though, couldn't it?
