### ISSUE TITLE
optimization bailouts

### ISSUE THREAD

**Issue by jamini87** [chrisbottin/xml-formatter#29]
Using this package in Angular 11 cause warning: "CommonJS or AMD dependencies can cause optimization bailouts."

**Comment by chrisbottin** [comment]
Thanks @jamini87 for the notification.

This is probably due to the CommonJS export. This code will be updated soon to use ES6 export.

**Comment by onpaws** [comment]
My Angular 13 app, with xml-formatter v2.6.0 says this when I `ng build`:
```
Warning: app/my-code.ts depends on 'xml-formatter'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

Is there an ES6 export version of this package available? Thank you

**Comment by chrisbottin** [comment]
I will create one shortly. Please watch the repo.
