### ISSUE TITLE
Can't import in ES6

### ISSUE THREAD

**Issue by asklar** [chrisbottin/xml-formatter#31]
I'm trying to use this module in some es6 typescript code, but I get this error:

```
error TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.
```

Any chance this library can be updated to support ES6?

**Comment by chrisbottin** [comment]
Hi @asklar,

Anything preventing you from turning on 'esModuleInterop' flag and referencing its default export as the error suggests?

It should work with this 'esModuleInterop' setting.

**Comment by asklar** [comment]
thanks - I was able to import it into our typescript project with `const formatter = require('xml-formatter');`
