### ISSUE TITLE
New line on content even with collapse content

### ISSUE THREAD

**Issue by dejawho** [chrisbottin/xml-formatter#42]
Hi,
when I'm formatting my XML I got the textual content of the node formatted too, even while using collapseContent = true, ie 

`<parent><text>my text</text></parent>
`

is formatted like

```
<parent>
    <text>
        my text
    </text>
</parent>
```

but I'm expecting something like

```
<parent>
<text>my text</text>
</parent>
```

I found this problem in 2.5.1, I've updated to 2.6 but I have still the same problem

**Comment by chrisbottin** [comment]
Hi,

This functionality is covered by this test https://github.com/chrisbottin/xml-formatter/blob/master/test/index.js#L36.

You see the input XML is https://github.com/chrisbottin/xml-formatter/blob/master/test/data3/xml1-input.xml and output is https://github.com/chrisbottin/xml-formatter/blob/master/test/data3/xml1-output.xml which similar to your case.

I've also tested with your XML and I'm getting the expected output.

Please ensure you have the latest version 2.6.0 correctly installed.

**Comment by dejawho** [comment]
I'm using the last version, at least the node_modules instance of xml-formatter in its package has a 2.6.0 version.
The problem could be related to CDATA node that are formatted and not considered like text, the one I did in the op was just a general example, I will attach a real example of the problem with both unformatted and formatted content
[formatted.txt](https://github.com/chrisbottin/xml-formatter/files/7989131/formatted.txt)
[unformatted.txt](https://github.com/chrisbottin/xml-formatter/files/7989135/unformatted.txt)
As you can see the CDATA are formatted into a new line

**Comment by chrisbottin** [comment]
I see. Yes, CDATA are treated as elements hence why they are added onto the next line.

I suppose they should be treated like text instead so we can consider this as a bug.

I will provide a fix shortly.

**Comment by dejawho** [comment]
Thank you very much

**Comment by chrisbottin** [comment]
version 2.6.1 should address your issue

**Comment by dejawho** [comment]
Hi, I confirm the fix is working, thank you
