### ISSUE TITLE
how to do the text in custom tags be inline

### ISSUE THREAD

**Issue by joneldiablo** [chrisbottin/xml-formatter#5]
this is the result of a part of my xml file:
```
                     <File>
                        <FileName>
                            929781356949_1_01.flac
                        </FileName>
                        <FilePath>
                            /
                        </FilePath>
                        <URL>
                            /929781356949_1_01.flac
                        </URL>
                        <HashSum>
                            <HashSum>
                                2c50aa9982e97f491ebaab11d7997ad9
                            </HashSum>
                            <HashSumAlgorithmType>
                                MD5
                            </HashSumAlgorithmType>
                        </HashSum>
                    </File>
```
but I want this:
```
                    <File>
                        <FileName>929781356949_1_01.flac</FileName>
                        <FilePath>/</FilePath>
                        <URL>/929781356949_1_01.flac</URL>
                        <HashSum>
                            <HashSum>2c50aa9982e97f491ebaab11d7997ad9</HashSum>
                            <HashSumAlgorithmType>MD5</HashSumAlgorithmType>
                        </HashSum>
                    </File>
```

its there possible to fix them?

**Comment by chrisbottin** [comment]
Hi,

I think it's related to this issue https://github.com/chrisbottin/xml-formatter/issues/3.

I will see if I can add an option.

**Comment by chrisbottin** [comment]
@joneldiablo Please check out this branch https://github.com/chrisbottin/xml-formatter/tree/feature/new-collapseContent-option.

A new option `collapseContent` has been added which should do what you requested. 

Please confirm it works as expected before I merge this branch to master.

**Comment by chrisbottin** [comment]
> ok I'll check it!

**Comment by chrisbottin** [comment]
> ok I'll check it!

@joneldiablo Any news? Thanks

**Comment by joneldiablo** [comment]
yes, sorry. this works ok

**Comment by chrisbottin** [comment]
> yes, sorry. this works ok

That's great. Thanks

**Comment by kefir500** [comment]
@chrisbottin

I checked [this branch](https://github.com/chrisbottin/xml-formatter/tree/feature/new-collapseContent-option): the `collapseContent` works great for me, thank you.

Any plans on merging it to `master`?

**Comment by chrisbottin** [comment]
> Any plans on merging it to `master`?

Yes, it's done now.
