### ISSUE TITLE
getting error "TypeError: format is not a function"

### ISSUE THREAD

**Issue by karloscastaneda** [chrisbottin/xml-formatter#51]
seems like "format(xml)" does not work anymore as it logs out "format is not a function"

found out that "format.default(xml)" is the way to call this FN now

**Comment by chrisbottin** [comment]
Thanks for submitting this issue @karloscastaneda.

A new major version was released yesterday with a new module code generation which might have caused that issue.

I've just published a new version https://www.npmjs.com/package/xml-formatter/v/3.0.1 which should fix the issue.

Please try that version.

**Comment by chrisbottin** [comment]
Should be fixed in new version

**Comment by karloscastaneda** [comment]
Thanks a lot!
