### ISSUE TITLE
Importing package (at least in Angular) using CommonJS version instead of ESNext version

### ISSUE THREAD

**Issue by hamfastgamgee** [chrisbottin/xml-formatter#54]
When I try to use version 3.2.0 in my Angular app, I'm getting warnings about CommonJS causing optimization bailouts, a common message for actual CommonJS packages when using them in Angular.  This is easy to suppress, but it isn't the right thing to do if you have ESM as an option.  I know you are building both CommonJS and ESNext in these versions.  It would appear that the package.json instructions are pointing the compiler entirely to the CommonJS version instead of conditionally to either CommonJS or ESNext, leading to the warning.  (xml-parser-xo no longer throws this message in v4, but I think that's because there aren't actually any imports in there to flag it as CommonJS.)  I don't claim to know how to configure this myself since what libraries I have worked on were ESM only, but I found the following article which seems to describe the problem: https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html

**Comment by chrisbottin** [comment]
Hi @hamfastgamgee 

Thanks for the link that's useful to know, I will look into setting up this configuration.

In the meantime, you could try to import using `import xmlFormat from 'xml-formatter/dist/esnext';` to see if the warnings go away.

**Comment by chrisbottin** [comment]
Ok, thanks for trying.

I will look into providing a Hybrid NPM module shortly.

**Comment by chrisbottin** [comment]
@hamfastgamgee this should be fixed now in the new version 3.2.1

If you are still having problems, please reopen this ticket.

**Comment by hamfastgamgee** [comment]
Just closing the loop: This did in fact fix the problem and Angular no longer grabs the CommonJS version.
