### ISSUE TITLE
Cannot parse XML with ENTITY definitions

### ISSUE THREAD

**Issue by busucu** [chrisbottin/xml-formatter#60]
First of all, thank you for all the efforts you put in to this library. Below xml is copied from https://github.com/chrisbottin/xml-parser and it can be formatted:

    const xml = `<?xml version="1.0" encoding="utf-8"?>
    
    <?xml-stylesheet href="foo.xsl" type="text/xsl" ?>
    <!DOCTYPE foo SYSTEM "foo.dtd">
    <foo><![CDATA[some text]]> content</foo>`;

However, it cannot be formatted after adding an ENTITY:

    const xml = <?xml version="1.0" encoding="utf-8"?>
    
    <?xml-stylesheet href="foo.xsl" type="text/xsl" ?>
    <!DOCTYPE foo [ <!ENTITY myentity "my entity value" > ]>
    <foo><![CDATA[some text]]> content</foo>

Console shows an error with the message "ERROR Error: Failed to parse XML".

**Comment by chrisbottin** [comment]
Thanks for raising that. I will look into this issue, hopefully it's a quick fix.

**Comment by busucu** [comment]
Thank you. I hope so, too.

**Comment by chrisbottin** [comment]
Fixed in version `3.4.1`

**Comment by busucu** [comment]
Awesome, thank you again:)
