### ISSUE TITLE
Cannot parse XML with DOCTYPE and without ENTITY definitions

### ISSUE THREAD

**Issue by busucu** [chrisbottin/xml-formatter#61]
(Related to #60 )

We parse and modify some XML documents with JavaScript and use xmlFormatter to show the XML string formatted. Some XMLs have empty ENTITY definitions list, such as `<!DOCTYPE xmldata []>`. If we parse the XML and serialize it back to string, it becomes `<!DOCTYPE xmldata>` and this XML cannot be parsed by xmlFormatter. 

```
// xmlContent starts with <!DOCTYPE xmldata []> and xmlFormatter works here
formattedXml = xmlFormatter(xmlContent, formatOptions); 

// parse and modify the xml
var xmlDoc = (new DOMParser()).parseFromString(xmlContent, "text/xml");

// serialize xml back to string
xmlContent = new XMLSerializer().serializeToString(xmlDoc);

// xmlContent starts with <!DOCTYPE xmldata> and xmlFormatter does not work here
formattedXml = xmlFormatter(xmlContent, formatOptions); // throws exception
```

**Comment by chrisbottin** [comment]
@busucu sorry for the late reply.

The issue should be fixerd in the version `4.1.1` of the package `xml-parser-xo`.

**Comment by busucu** [comment]
Awesome, thank you so much.
