### ISSUE TITLE
Preserve line for text nodes

### ISSUE THREAD

**Issue by mynameisvasco** [chrisbottin/xml-formatter#67]
Hello.
I'm trying to have text nodes on the same line that his next sibbling.
Is it possible to achieve using latest version ?

Example:

```xml
<choice>
  <abbr>ĩ</abbr>
  <expan>in</expan>
</choice>
casa de caualei<add place="margin">ro</add>

**Comment by chrisbottin** [comment]
Hi @mynameisvasco,

Sorry I've just seen your question.

The XML you provided is not valid as it needs a root element but perhaps you just provided a snapshot of it.

With the following structure and the use of `xml:space="preserve"`, you should be able to achieve what you need.

### Input XML
```xml
<root><choice><abbr>ĩ</abbr><expan>in</expan></choice><sentence xml:space="preserve">casa de caualei<add place="margin">ro</add><sentence></root>
```

### Output XML
```xml
<root>
  <choice>
    <abbr>ĩ</abbr>
    <expan>in</expan>
  </choice>
  <sentence xml:space="preserve">casa de caualei<add place="margin">ro</add><sentence>
</root>
```
