### ISSUE TITLE
v3.6.1 New Typescript requirement - Won't compile unless adding allowSyntheticDefaultImports

### ISSUE THREAD

**Issue by bjornharvold** [chrisbottin/xml-formatter#70]
```
Error message:

can only be default-imported using the 'allowSyntheticDefaultImports' flag

import xmlFormat from 'xml-formatter';
            ~~~~~~~~~
node_modules/xml-formatter/dist/types/index.d.ts:57:1
export = formatXml;

This module is declared with 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.
```

**Comment by chrisbottin** [comment]
Hey @bjornharvold,

Thanks for raising this issue. The recent changes to sort https://github.com/chrisbottin/xml-formatter/issues/68 have caused this regression.

I think I will have to revert them today and come up with a different solution.

**Comment by chrisbottin** [comment]
I've now reverted the changes made for https://github.com/chrisbottin/xml-formatter/issues/68.

Version `3.6.2` should fix this.

**Comment by bjornharvold** [comment]
Yes, that fixed it 🦸‍♂️🍺
