### ISSUE TITLE
Incompatible with TypeScript and "type": "module"

### ISSUE THREAD

**Issue by nwalters512** [chrisbottin/xml-formatter#72]
Reproduction: https://github.com/nwalters512/xml-formatter-typescript-repro

TypeScript on the consuming end ends up confused. My understanding (which may or may not be correct): it sees that the export is a CommonJS file, but the types are declared with `export default ...`, so it believes that there's actually a `default` property on the exports, and thus it wants this package to be used like this:

```ts
import formatXml from 'xml-formatter';

console.log(formatXml.default('<foo>'));
```

However, the `.default` property does not exist at runtime. So one can either add `.default` to make TypeScript happy but end up with a runtime error, or not add `.default`, in which case the code runs but TypeScript thinks it's incorrect.

Dual-publishing ESM and CJS with types is really, really tricky to do correctly. My unsolicited advice: it's probably best to either switch back to shipping plain CJS, or bite the bullet and go ESM-only.

If you want to make dual-publishing work, I believe the following would be sufficient:

- Rename `dist/cjs/index.js` to `dist/cjs/index.cjs`
  - Alternatively, add `dist/cjs/package.json` with `{"type":"commonjs"}`
- Update `package.json` with roughly the following:

```json
{
  "type": "module",
  "main": "./dist/cjs/index.cjs",
  "module": "./dist/esm/index.js",
  "types": "./dist/types/index.d.ts",
  "exports": {
    "./package.json": "./package.json",
    ".": {
      "import": "./dist/esm/index.js",
      "require": "./dist/cjs/index.cjs",
      "types": "./dist/types/index.d.ts"
    }
  }
}
```

If you'd be OK with this change, I'd be happy to open a PR!

**Comment by chrisbottin** [comment]
Thanks @nwalters512 for submitting your issue and well-detailed information.

Yes it's very difficult to get the package to work for both ES module and CommonJS especially with all the different configurations we can have in `tsconfig.json`.

As it is now the package should work with ES module and CommonJS if you use the following `tsconfig.json`.

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "rootDir": "./src"
  }
}
```

If that's not suitable for you, I'm happy if you want to create a PR with changes that will work with most, if not all configurations.

**Comment by chrisbottin** [comment]
Closing after suggesting workaround.
