### ISSUE TITLE
Error when tailing blank in close tag

### ISSUE THREAD

**Issue by emn178** [chrisbottin/xml-formatter#74]
In this case:
```XML
<tag></tag >
```

It throws error
```
Error: Failed to parse XML
```

but I try others parser, all of them allow this. Seems a bug?

**Comment by chrisbottin** [comment]
Yes, the parser could be a little more forgiving.

I will take a look.

**Comment by chrisbottin** [comment]
Fixed in version `3.6.3`.

Thanks @emn178 for fixing the issue.
