### ISSUE TITLE
Line break is Windows-type

### ISSUE THREAD

**Issue by chrisben** [chrisbottin/xml-formatter#9]
Line breaks appear as "\r\n" (CRLF), which is all fine on Windows but for the rest of the world it's "\n" (LF).
Could you perhaps provide an option to override that default line break?

**Comment by chrisbottin** [comment]
Yes, it's quite easy to provide an option for that. 

If you would like to do it, you can submit a pull request otherwise I will try and do it as soon as I can.

Thank you.

**Comment by chrisbottin** [comment]
Added in version https://github.com/chrisbottin/xml-formatter/releases/tag/1.2.0

**Comment by chrisben** [comment]
Thanks!
